# Changes here will be overwritten by Copier
_commit: 0.6.0
_src_path: git@github.com:LedgerHQ/python.copier.git
author_email: axel.haustant@ledger.fr
author_fullname: Axel Haustant
features:
- docs
- notify_releases
github_repository: mkdocs-ledger
github_username: noirbizarre
kind: lib
project_description: A MkDocs Ledger theme based on Material for MkDocs
project_name: mkdocs-ledger
project_slug: mkdocs-ledger
public: true
python_distribution: mkdocs-ledger
python_package: mkdocs_ledger
use_src: false
