default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
  - post-checkout
  - post-merge

default_stages:
  - pre-commit

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: "tests/data/.+"
      - id: check-yaml
        exclude: ^mkdocs\.yml
      - id: check-yaml
        name: Check yaml unsafe
        alias: check-yaml-unsafe
        description: Check yaml with custom constructors
        args: [--unsafe]
        files: mkdocs.yml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-toml
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.24.0
    hooks:
      - id: commitizen
        additional_dependencies:
          - emotional

  - repo: https://github.com/pdm-project/pdm
    rev: 2.11.1
    hooks:
      - id: pdm-lock-check
      - id: pdm-sync

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.2
    hooks:
      - id: check-github-workflows
      - id: check-dependabot

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: docs/.*\.pyi?$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      additional_dependencies: [tomli]
      args: ["--write-changes"]
      # Ignore typos in changelog, they will be overridden
      exclude: ^CHANGELOG\.md$

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.11.0
    hooks:
    - id: markdownlint-cli2
      args: ["--fix"]
      exclude: ^CHANGELOG\.md$
