# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: Ledger theme for MkDocs
site_author: Ledger
repo_name: LedgerHQ/mkdocs-ledger
repo_url: https://github.com/LedgerHQ/mkdocs-ledger
edit_uri: edit/main/docs/

theme: ledger

plugins:
  - material/search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
  - gen-files:
      scripts:
      - scripts/gendocs.py
  - literate-nav:
      nav_file: SUMMARY.md


markdown_extensions:
  - mkdocs-click
  - admonition
  - github-callouts
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Documentation: index.md
  - Showcase:
    - Click: cli.md
    - Docstrings: docstrings.md
    - OpenAPI: openapi.md
    - Mermaid: mermaid.md
  - API Reference: reference/
  - Contributing: contributing.md
  - Housekeeping: housekeeping.md
  - Changelog: changelog.md

watch:
  - README.md
  - CHANGELOG.md
  - CONTRIBUTING.md
  - mkdocs_ledger

# Footer: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/
copyright: Copyright &copy; 2024 Ledger Enterprise
extra:
  version:
    provider: mike
  social:
    - name: Github repository
      icon: fontawesome/brands/github
      link: https://github.com/LedgerHQ/mkdocs-ledger
