name: 👮 CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Force colored output in Python apps supporting it
  PY_COLORS: "1"

jobs:
  lint:
    name: 🕵 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: LedgerHQ/actions/pdm/lint@main

  tests:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: LedgerHQ/actions/pdm/test@main
        with:
          python-version: ${{ matrix.python-version }}
          github-token: ${{ secrets.CI_BOT_TOKEN }}

  build-docs:
    name: 📖 Build documentation
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: LedgerHQ/actions/pdm/doc/build@main
        with:
          openapi: false
          site: true

  deploy-docs:
    name: 📚 Deploy documentation
    needs: build-docs
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: LedgerHQ/actions/pdm/doc/publish@main
        with:
          openapi: false
          site: true
