name: 🚀 Release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Kind of increment (optional)
        options:
          - ''
          - MAJOR
          - MINOR
          - PATCH
        default: ''
        required: false

jobs:
  check:
    name: 👮 Check pre-conditions
    runs-on: ubuntu-latest
    steps:
      - name: Ensure CI success
        uses: noirbizarre/need-checks@0.1
        with:
          workflow: ci.yml
          token: ${{ secrets.CI_BOT_TOKEN }}

  release:
    name: 🚀 Bump & publish release
    needs: check
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.release.outputs.url }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: LedgerHQ/actions/pdm/release@main
        id: release
        with:
          kind: lib
          increment: ${{ inputs.increment }}
          pypi-token: ${{ secrets.PYPI_PUBLIC_API_TOKEN }}
          github-token: ${{ secrets.CI_BOT_TOKEN }}
          public: true

  notify:
    name: 📣 Notify
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Notify Slack
        uses: LedgerHQ/actions/slack/release@main
        if: env.HAS_SLACK_WEBHOOK != null
        with:
          project: mkdocs-ledger
          version: ${{ needs.release.outputs.version }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github-release: ${{ needs.release.outputs.url }}
          docker: ghcr.io/ledgerhq/${{ github.event.repository.name }}:${{ needs.release.outputs.version }}
          documentation: ${{ needs.release.outputs.documentation }}
        env:
          HAS_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
